// Copyright 2025 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter_convert_graphics` with arguments:
//    format | rgb565
//    output | gfx
//    input  | sleep.gif

#pragma once

#include <qp.h>

// 24x32
extern const uint32_t gfx_sleep_length;
extern const uint8_t  gfx_sleep[2819];

// 24x60
extern const uint32_t gfx_hop_length;
extern const uint8_t  gfx_hop[7258];

// 24x40
extern const uint32_t gfx_twirl_length;
extern const uint8_t  gfx_twirl[6418];
